### ISSUE TITLE
Images missing when printing

### ISSUE THREAD

**Issue by mxwe** [amyjko/foundations-of-information#90] opened 2023-12-14 03:15 UTC
Hi Amy, I am trying to create a PDF of the whole book, which is offered through the print link, but only get the text with no images. I have tried to print to a PDF using a few different methods and do not get images in any of the options I have tried. The images are important. Do you have any suggestions? I'd like to use to the text with the hypothesis tool in Canvas. ~Wes

**Comment by amyjko** [comment] 2023-12-14 15:35
Hi @mxwe! Can you share which browser, browser version, operating system, and operating system version you're using? Printing functionality is very different between browsers and operating systems, so I'd need to know which specific one you're using to reproduce and diagnose the issue.

**Comment by mxwe** [comment] 2023-12-14 18:26
I am using MacOS 13.4.1 and viewing the website using Firefox 120.0.1.

I have printed from the Firefox print screen Save to PDF option as well as the Print using the system dialogue option with Open in Preview and Save as PDF options. I have not tried a different browser yet.

Wes


WES ELI KING, PHD

hear my name<https://namedrop.io/weseliking>

my pronouns<https://www.mypronouns.org/what-and-why>: they, he

Assistant Teaching Professor

UW Information School
***@***.***  /  washington.edu

[cid:29e83b8f-467f-445c-82bf-831af5be445a]

________________________________

**Comment by amyjko** [comment] 2023-12-14 19:23
Interesting. I tested on mac OS 14.1.1 with Firefox 120.0.1 and the print dialog preview shows the images, as does the exported PDF. Are you seeing any error messages when you attempt to print? Have the images finished loading? (When I create the PDF, it's a massive 120 MB, so if you're on a slow internet connection, it may take some time to download all of them).

**Comment by mxwe** [comment] 2023-12-15 02:18
The print dialog preview shows the images and I waited to ensure the images were loaded in the browser before requesting print/save to PDF. I was on campus when I attempted to create a PDF yesterday, so slow internet was probably not an issue. What would be most helpful for you in demonstrating the problem or resolving the issue? I can do a screen recording, send PDF files, etc. Since you have successfully created a PDF version that includes images, would you share it with me on Google Drive or OneDrive while we sort out the issue?

**Comment by amyjko** [comment] 2023-12-15 02:27
A screen recording, plus any errors you see on the web console, would be most helpful. (Select the Web Console panel in the Web Developer Tools, accessible from the Browser Tools submenu). I have done a bit of research and it seems many people have issues with Firefox loading images on a page, but not when printing, but there are many different reasons for this behavior. So console errors would help reveal any causes (if there are any errors).

Here's an export I made in Chrome:

https://drive.google.com/file/d/1ZH2GzgNXMFYgSKP6KIK-HGC6zlhH6XdL/view?usp=sharing

I was also able to make the same export in Firefox and Safari.

**Comment by mxwe** [comment] 2023-12-15 23:03
I'm having trouble with uploading the screen recording from home but will work on it this weekend. Here are screenshots of errors from Browser Console (Tools>Browser Tools>Browser Console) and Web Developer Console (Tools>Browser Tools>Web Developer Tools>Console
![Browser Console](https://github.com/amyjko/foundations-of-information/assets/35820392/4d5f5142-5f3b-4186-9f5b-41050cb3bedc)
![Web Developer Console](https://github.com/amyjko/foundations-of-information/assets/35820392/eda8a445-4f22-485e-8ed6-0eed6c3f09ad)

**Comment by amyjko** [comment] 2023-12-15 23:36
Thanks! Alas, those look like plugin errors, and nothing to do with the book.

**Comment by mxwe** [comment] 2023-12-16 01:23
I've disabled all extensions and plugins in Firefox and it still doesn't work, so I will have to dig deeper on that one.

I was able to get a PDF using Chrome.

Pagination was different than the PDF you shared with me, but it looks like the book is working in most cases, which I guess is the best you can hope for in this heterogeneous platform/browser/plugin world.

**Comment by amyjko** [comment] 2023-12-16 01:25
I'll close this for now, since your problem is solved. Firefox printing will have to remain a mystery for now :)

**Closed by amyjko** 2023-12-16 01:25 UTC
Labels: error
