### ISSUE TITLE
PDF of Foundations of Information

### ISSUE THREAD

**Issue by IntranetFocus** [amyjko/foundations-of-information#75] opened 2022-01-21 14:22 UTC
I only seem to be able to view a web page of the complete book and am unable to either save it as a PDF or export it

**Comment by amyjko** [comment] 2022-01-21 15:24
Thanks for reporting! This is actually the intended behavior at the moment: the print link opens up a page with all of the chapters and then you can use your browser’s features to print or save the web page as a PDF. The website itself doesn’t offer any of the printing or saving functionality.

Amy J. Ko, Ph.D. (she/her)
Professor • The Information School • CSE
University of Washington • Seattle
http://faculty.uw.edu/ajko

I read/write email weekday mornings.
On Jan 21, 2022, 6:23 AM -0800, IntranetFocus ***@***.***>, wrote:

Reopened #75<https://github.com/amyjko/foundations-of-information/issues/75>.

**Comment by amyjko** [comment] 2022-03-12 16:51
Closing; this is supported through browser print to PDF functionality.

**Closed by amyjko** 2022-03-12 16:51 UTC
